/**
 * 榮譽成就與稱號系統定義 (ES Module)
 * 包含成就分類、稀有度等級、成就清單與段位系統
 */

export const ACHIEVEMENT_CATEGORIES = {
  ALL: 'ALL',
  VICTORY: 'VICTORY',       // 陣營征途
  ROLE_SKILL: 'ROLE_SKILL', // 神職絕技
  MIND_GAME: 'MIND_GAME',   // 心理博弈
  SPECIAL: 'SPECIAL',       // 社交與彩蛋
};

export const CATEGORY_LABELS = {
  [ACHIEVEMENT_CATEGORIES.ALL]: { label: '全部成就', icon: '🏆' },
  [ACHIEVEMENT_CATEGORIES.VICTORY]: { label: '陣營征途', icon: '⚔️' },
  [ACHIEVEMENT_CATEGORIES.ROLE_SKILL]: { label: '神職絕技', icon: '✨' },
  [ACHIEVEMENT_CATEGORIES.MIND_GAME]: { label: '心理博弈', icon: '🎭' },
  [ACHIEVEMENT_CATEGORIES.SPECIAL]: { label: '社交彩蛋', icon: '🌟' },
};

export const ACHIEVEMENT_TIERS = {
  BRONZE: {
    id: 'BRONZE',
    name: '青銅',
    color: 'from-amber-700/80 to-amber-900/80',
    border: 'border-amber-700/60',
    text: 'text-amber-400',
    badge: 'bg-amber-950/80 text-amber-300 border-amber-800',
    glow: 'shadow-amber-950/40',
    icon: '🥉',
  },
  SILVER: {
    id: 'SILVER',
    name: '白銀',
    color: 'from-slate-400/80 to-slate-600/80',
    border: 'border-slate-400/60',
    text: 'text-slate-200',
    badge: 'bg-slate-900/90 text-slate-200 border-slate-600',
    glow: 'shadow-slate-500/20',
    icon: '🥈',
  },
  GOLD: {
    id: 'GOLD',
    name: '黃金',
    color: 'from-yellow-400/80 to-amber-500/80',
    border: 'border-yellow-500/80',
    text: 'text-yellow-300',
    badge: 'bg-yellow-950/80 text-yellow-300 border-yellow-600',
    glow: 'shadow-yellow-500/30',
    icon: '🥇',
  },
  LEGEND: {
    id: 'LEGEND',
    name: '傳奇',
    color: 'from-purple-500/90 via-pink-500/90 to-rose-500/90',
    border: 'border-pink-500/90',
    text: 'text-pink-300',
    badge: 'bg-purple-950/90 text-pink-300 border-pink-500',
    glow: 'shadow-pink-500/50',
    icon: '💎',
  },
};

/**
 * 榮譽段位/稱號等級定義 (依累計 AP 成就點數晉升)
 */
export const HONOR_RANKS = [
  { minAp: 0, title: '初級見習生', badge: '🌱 見習 Lv.1', color: 'text-zinc-400 border-zinc-700 bg-zinc-900/80' },
  { minAp: 50, title: '村莊守夜者', badge: '🛡️ 守夜 Lv.2', color: 'text-emerald-400 border-emerald-700 bg-emerald-950/80' },
  { minAp: 120, title: '明月追尋者', badge: '🌙 追尋 Lv.3', color: 'text-sky-400 border-sky-700 bg-sky-950/80' },
  { minAp: 220, title: '黑夜審判官', badge: '⚖️ 審判 Lv.4', color: 'text-indigo-400 border-indigo-700 bg-indigo-950/80' },
  { minAp: 360, title: '博弈大師', badge: '♟️ 大師 Lv.5', color: 'text-purple-400 border-purple-700 bg-purple-950/80' },
  { minAp: 550, title: '聖殿執法官', badge: '⚔️ 執法 Lv.6', color: 'text-amber-400 border-amber-600 bg-amber-950/80' },
  { minAp: 800, title: '暗夜主宰者', badge: '👑 領主 Lv.7', color: 'text-orange-400 border-orange-600 bg-orange-950/80' },
  { minAp: 1100, title: '狼人殺傳奇宗師', badge: '💎 宗師 Lv.8', color: 'text-rose-400 border-rose-500 bg-rose-950/80' },
  { minAp: 1500, title: '無上造物神話', badge: '🌌 神話 MAX', color: 'text-fuchsia-300 border-fuchsia-400 bg-fuchsia-950/80 animate-pulse' },
];

/**
 * 完整 28 項成就詳細定義
 */
export const ACHIEVEMENTS = [
  // ================= 陣營征途 (VICTORY) =================
  {
    id: 'first_game',
    title: '初入村莊',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🏡',
    description: '完成第 1 場狼人殺對局（無論勝負）。',
    rewardTitle: '新晉村民',
    ap: 10,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.gamesPlayed || 0),
    isUnlocked: (s) => (s.gamesPlayed || 0) >= 1,
  },
  {
    id: 'veteran_5',
    title: '百戰先鋒',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '🎖️',
    description: '累計完成 5 場狼人殺對局。',
    rewardTitle: '資深守夜人',
    ap: 25,
    maxProgress: 5,
    getProgress: (s) => Math.min(5, s.gamesPlayed || 0),
    isUnlocked: (s) => (s.gamesPlayed || 0) >= 5,
  },
  {
    id: 'veteran_20',
    title: '圓桌元老',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '👑',
    description: '累計完成 20 場狼人殺對局。',
    rewardTitle: '傳奇元老',
    ap: 50,
    maxProgress: 20,
    getProgress: (s) => Math.min(20, s.gamesPlayed || 0),
    isUnlocked: (s) => (s.gamesPlayed || 0) >= 20,
  },
  {
    id: 'good_victor_1',
    title: '正義之光',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '☀️',
    description: '作為好人陣營玩家獲得 1 場勝利。',
    rewardTitle: '破曉者',
    ap: 10,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.goodWins || 0),
    isUnlocked: (s) => (s.goodWins || 0) >= 1,
  },
  {
    id: 'good_victor_5',
    title: '村莊守護者',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '🛡️',
    description: '作為好人陣營玩家累計獲得 5 場勝利。',
    rewardTitle: '光明燈塔',
    ap: 30,
    maxProgress: 5,
    getProgress: (s) => Math.min(5, s.goodWins || 0),
    isUnlocked: (s) => (s.goodWins || 0) >= 5,
  },
  {
    id: 'wolf_victor_1',
    title: '夜幕低垂',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🐺',
    description: '作為狼人陣營玩家獲得 1 場勝利。',
    rewardTitle: '暗影爪痕',
    ap: 10,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.wolfWins || 0),
    isUnlocked: (s) => (s.wolfWins || 0) >= 1,
  },
  {
    id: 'wolf_victor_5',
    title: '暗夜主宰',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '🌕',
    description: '作為狼人陣營玩家累計獲得 5 場勝利。',
    rewardTitle: '嗜血狼王',
    ap: 30,
    maxProgress: 5,
    getProgress: (s) => Math.min(5, s.wolfWins || 0),
    isUnlocked: (s) => (s.wolfWins || 0) >= 5,
  },
  {
    id: 'win_streak_3',
    title: '勢不可擋',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '🔥',
    description: '達成連續 3 場獲勝的連勝紀錄。',
    rewardTitle: '連勝霸主',
    ap: 35,
    maxProgress: 3,
    getProgress: (s) => Math.min(3, s.maxStreak || 0),
    isUnlocked: (s) => (s.maxStreak || 0) >= 3,
  },
  {
    id: 'flawless_win',
    title: '不滅神話',
    category: ACHIEVEMENT_CATEGORIES.VICTORY,
    tier: ACHIEVEMENT_TIERS.LEGEND,
    icon: '💎',
    description: '以己方陣營全體成員零陣亡達成完封獲勝！',
    rewardTitle: '不滅神話',
    ap: 50,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.flawlessWins || 0),
    isUnlocked: (s) => (s.flawlessWins || 0) >= 1,
  },

  // ================= 神職絕技 (ROLE_SKILL) =================
  {
    id: 'seer_wolf_hunter',
    title: '洞若觀火',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '🔮',
    description: '使用預言家累計查驗出 3 名狼人。',
    rewardTitle: '神之眼',
    ap: 25,
    maxProgress: 3,
    getProgress: (s) => Math.min(3, s.seerWolfFound || 0),
    isUnlocked: (s) => (s.seerWolfFound || 0) >= 3,
  },
  {
    id: 'seer_legend',
    title: '全知之鏡',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '👁️',
    description: '單局預言家成功查出 2 名以上狼人。',
    rewardTitle: '全知大導師',
    ap: 40,
    maxProgress: 2,
    getProgress: (s) => Math.min(2, s.seerWolfFoundSingleGame || 0),
    isUnlocked: (s) => (s.seerWolfFoundSingleGame || 0) >= 2,
  },
  {
    id: 'witch_savior',
    title: '妙手回春',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🧪',
    description: '女巫成功使用解藥救活被狼刀襲殺的玩家。',
    rewardTitle: '靈藥聖手',
    ap: 20,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.witchSaved || 0),
    isUnlocked: (s) => (s.witchSaved || 0) >= 1,
  },
  {
    id: 'witch_poison_wolf',
    title: '致命劇毒',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '☠️',
    description: '女巫使用毒藥精準毒殺一名狼人。',
    rewardTitle: '劇毒大師',
    ap: 25,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.witchPoisonedWolf || 0),
    isUnlocked: (s) => (s.witchPoisonedWolf || 0) >= 1,
  },
  {
    id: 'witch_dual_master',
    title: '神級女巫',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.LEGEND,
    icon: '🧙‍♀️',
    description: '同一局內成功救治隊友並毒殺狼人（雙藥全中）。',
    rewardTitle: '命運織女',
    ap: 50,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.witchDualHitSingleGame || 0),
    isUnlocked: (s) => (s.witchDualHitSingleGame || 0) >= 1,
  },
  {
    id: 'guard_iron_wall',
    title: '金湯之盾',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '🛡️',
    description: '守衛成功同守狼人襲殺目標，創造平安夜！',
    rewardTitle: '嘆息之壁',
    ap: 30,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.guardSaved || 0),
    isUnlocked: (s) => (s.guardSaved || 0) >= 1,
  },
  {
    id: 'guard_guardian_angel',
    title: '鋼鐵守護',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '🏰',
    description: '守衛累計成功守護平安夜達 3 次。',
    rewardTitle: '永恆守衛神',
    ap: 40,
    maxProgress: 3,
    getProgress: (s) => Math.min(3, s.guardSaved || 0),
    isUnlocked: (s) => (s.guardSaved || 0) >= 3,
  },
  {
    id: 'hunter_bullseye',
    title: '槍響魂斷',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '💥',
    description: '獵人出局開槍精準擊斃狼人。',
    rewardTitle: '百步穿楊',
    ap: 30,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.hunterShotWolf || 0),
    isUnlocked: (s) => (s.hunterShotWolf || 0) >= 1,
  },
  {
    id: 'knight_holy_strike',
    title: '聖劍裁決',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '⚔️',
    description: '騎士白天發動決鬥成功斬殺狼人！',
    rewardTitle: '聖殿騎士長',
    ap: 35,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.knightKilledWolf || 0),
    isUnlocked: (s) => (s.knightKilledWolf || 0) >= 1,
  },
  {
    id: 'silencer_whisper',
    title: '禁語之印',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🤐',
    description: '禁言長老累計成功指定禁言 3 次。',
    rewardTitle: '封印者',
    ap: 20,
    maxProgress: 3,
    getProgress: (s) => Math.min(3, s.silencedCount || 0),
    isUnlocked: (s) => (s.silencedCount || 0) >= 3,
  },
  {
    id: 'dream_master',
    title: '莊周夢蝶',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.SILVER,
    icon: '💤',
    description: '攝夢人連續兩夜夢同一人致死狼人。',
    rewardTitle: '造夢大師',
    ap: 30,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.dreamKilledWolf || 0),
    isUnlocked: (s) => (s.dreamKilledWolf || 0) >= 1,
  },
  {
    id: 'cupid_matchmaker',
    title: '愛神之箭',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '💘',
    description: '作為邱比特或情侶身分獲得最終勝利。',
    rewardTitle: '命定紅線',
    ap: 35,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.loverWins || 0),
    isUnlocked: (s) => (s.loverWins || 0) >= 1,
  },
  {
    id: 'idiot_reveal',
    title: '大智若愚',
    category: ACHIEVEMENT_CATEGORIES.ROLE_SKILL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🤡',
    description: '白痴被白天放逐投票翻牌免死存活。',
    rewardTitle: '天選小丑',
    ap: 20,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.idiotRevealed || 0),
    isUnlocked: (s) => (s.idiotRevealed || 0) >= 1,
  },

  // ================= 心理博弈 (MIND_GAME) =================
  {
    id: 'lone_wolf_survivor',
    title: '殘狼翻盤',
    category: ACHIEVEMENT_CATEGORIES.MIND_GAME,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '🐺',
    description: '作為最後一名存活的孤狼逆風翻盤獲勝。',
    rewardTitle: '獨行夜狼',
    ap: 45,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.loneWolfWon || 0),
    isUnlocked: (s) => (s.loneWolfWon || 0) >= 1,
  },
  {
    id: 'wolf_oscar',
    title: '奧斯卡影帝',
    category: ACHIEVEMENT_CATEGORIES.MIND_GAME,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '🎭',
    description: '作為狼人獲勝且整場遊戲未曾被投票放逐過。',
    rewardTitle: '千面偽裝者',
    ap: 40,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.wolfOscarWins || 0),
    isUnlocked: (s) => (s.wolfOscarWins || 0) >= 1,
  },
  {
    id: 'night_survivor_3',
    title: '黑夜行者',
    category: ACHIEVEMENT_CATEGORIES.MIND_GAME,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '👣',
    description: '在單局中成功存活度過至少 3 個黑夜。',
    rewardTitle: '潛行大師',
    ap: 20,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.nightSurvivorCount || 0),
    isUnlocked: (s) => (s.nightSurvivorCount || 0) >= 1,
  },
  {
    id: 'silver_water_survivor',
    title: '死裡逃生',
    category: ACHIEVEMENT_CATEGORIES.MIND_GAME,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '💧',
    description: '曾被女巫解藥救活並堅持戰鬥至遊戲獲勝。',
    rewardTitle: '幸運之星',
    ap: 20,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.silverWaterWon || 0),
    isUnlocked: (s) => (s.silverWaterWon || 0) >= 1,
  },

  // ================= 社交與彩蛋 (SPECIAL) =================
  {
    id: 'talkative',
    title: '雄辯演說家',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '💬',
    description: '累計在聊天室發言交流超過 15 次。',
    rewardTitle: '邏輯辯論家',
    ap: 15,
    maxProgress: 15,
    getProgress: (s) => Math.min(15, s.chatCount || 0),
    isUnlocked: (s) => (s.chatCount || 0) >= 15,
  },
  {
    id: 'voice_warrior',
    title: '聲入人心',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '🎙️',
    description: '開啟即時語音麥克風進行即時交流。',
    rewardTitle: '好聲音演說家',
    ap: 15,
    maxProgress: 1,
    getProgress: (s) => Math.min(1, s.voiceUsed || 0),
    isUnlocked: (s) => (s.voiceUsed || 0) >= 1,
  },
  {
    id: 'lore_master',
    title: '博覽群書',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    tier: ACHIEVEMENT_TIERS.BRONZE,
    icon: '📖',
    description: '查閱並瀏覽角色技能百科手冊至少 6 位角色。',
    rewardTitle: '博學賢者',
    ap: 15,
    maxProgress: 6,
    getProgress: (s) => Math.min(6, (s.loreViewedRoles || []).length),
    isUnlocked: (s) => ((s.loreViewedRoles || []).length) >= 6,
  },
  {
    id: 'collector_50',
    title: '榮譽收藏家',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    tier: ACHIEVEMENT_TIERS.GOLD,
    icon: '🏅',
    description: '解鎖超過 50% 的榮譽成就（14項以上）。',
    rewardTitle: '榮譽領主',
    ap: 50,
    maxProgress: 14,
    getProgress: (s) => Math.min(14, Object.keys(s.unlockedAchievements || {}).length),
    isUnlocked: (s) => Object.keys(s.unlockedAchievements || {}).length >= 14,
  },
  {
    id: 'collector_100',
    title: '狼人殺傳奇',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    tier: ACHIEVEMENT_TIERS.LEGEND,
    icon: '🌌',
    description: '達成全成就大滿貫（解鎖所有其餘成就）！',
    rewardTitle: '傳奇造物神',
    ap: 100,
    maxProgress: 27,
    getProgress: (s) => {
      const unlockedCount = Object.keys(s.unlockedAchievements || {}).filter((k) => k !== 'collector_100').length;
      return Math.min(27, unlockedCount);
    },
    isUnlocked: (s) => {
      const unlockedCount = Object.keys(s.unlockedAchievements || {}).filter((k) => k !== 'collector_100').length;
      return unlockedCount >= 27;
    },
  },
];

/**
 * 依據總 AP 計算當前玩家榮譽段位
 */
export function calculateHonorRank(totalAp) {
  let rank = HONOR_RANKS[0];
  for (let i = HONOR_RANKS.length - 1; i >= 0; i--) {
    if (totalAp >= HONOR_RANKS[i].minAp) {
      rank = HONOR_RANKS[i];
      const nextRank = HONOR_RANKS[i + 1] || null;
      const currentLevelMin = rank.minAp;
      const nextLevelMin = nextRank ? nextRank.minAp : rank.minAp + 500;
      const progressPercent = Math.min(
        100,
        Math.round(((totalAp - currentLevelMin) / (nextLevelMin - currentLevelMin)) * 100)
      );

      return {
        currentRank: rank,
        nextRank,
        totalAp,
        progressPercent,
        apToNext: nextRank ? nextRank.minAp - totalAp : 0,
      };
    }
  }
  return {
    currentRank: HONOR_RANKS[0],
    nextRank: HONOR_RANKS[1],
    totalAp,
    progressPercent: 0,
    apToNext: HONOR_RANKS[1].minAp - totalAp,
  };
}
